on:
  push:
    tags:
    - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
  build_wheel:
    runs-on: ubuntu-latest
    name: Build & Release mypyc wheels
    strategy:
      fail-fast: false
      matrix:
        python_version: [ 3.5, 3.6, 3.7, 3.8 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: run the build script
        uses: docker://quay.io/pypa/manylinux1_x86_64
        with:
          entrypoint: ./build-linux-wheels.sh
          args: ${{ matrix.python_version }}

      - name: Upload Release assets
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # JS script to workaround this issue:
          # https://github.com/actions/upload-release-asset/issues/47
          # Release all wheels built in wheelhouse/*.whl
          script: |
            const path = require('path');
            const fs = require('fs');
            const release_id = '${{ needs.create_release.outputs.id }}';
            for (let file of await fs.readdirSync('./wheelhouse/')) {
              if (path.extname(file) === '.whl') {
                console.log('uploadReleaseAsset', file);
                await github.repos.uploadReleaseAsset({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: release_id,
                  name: file,
                  data: await fs.readFileSync(`./${file}`)
                });
              }
            }
